export type PartyAvatarCategory = 'people' | 'animals' | 'other'

export type PartyAvatarVariant = 'static' | 'animated'

export type PartyAvatarAsset = {
  id: string
  label: string
  category: PartyAvatarCategory
  codepoint: string
  staticSrc: string
  animatedSrc: string
  animatedWebpSrc: string
  legacyGlyph?: string
}

const NOTO_EMOJI_BASE_URL = 'https://fonts.gstatic.com/s/e/notoemoji/latest'

function buildAsset({
  id,
  label,
  category,
  codepoint,
  legacyGlyph,
}: {
  id: string
  label: string
  category: PartyAvatarCategory
  codepoint: string
  legacyGlyph?: string
}): PartyAvatarAsset {
  return {
    id,
    label,
    category,
    codepoint,
    staticSrc: `${NOTO_EMOJI_BASE_URL}/${codepoint}/emoji.svg`,
    animatedSrc: `${NOTO_EMOJI_BASE_URL}/${codepoint}/512.gif`,
    animatedWebpSrc: `${NOTO_EMOJI_BASE_URL}/${codepoint}/512.webp`,
    legacyGlyph,
  }
}

export const PARTY_AVATAR_CATEGORY_LABELS: Record<PartyAvatarCategory, string> = {
  people: 'Ludzie',
  animals: 'Zwierzeta',
  other: 'Inne',
}

export const DEFAULT_PARTY_AVATAR_ID = 'smile'

export const PARTY_AVATARS: readonly PartyAvatarAsset[] = [
  buildAsset({ id: 'smile', label: 'Usmiech', category: 'people', codepoint: '1f604', legacyGlyph: '\u{1F604}' }),
  buildAsset({ id: 'smile-with-big-eyes', label: 'Wielki-usmiech', category: 'people', codepoint: '1f603', legacyGlyph: '\u{1F603}' }),
  buildAsset({ id: 'grin', label: 'Szczerbaty-usmiech', category: 'people', codepoint: '1f601', legacyGlyph: '\u{1F601}' }),
  buildAsset({ id: 'grinning', label: 'Szeroki-usmiech', category: 'people', codepoint: '1f600', legacyGlyph: '\u{1F600}' }),
  buildAsset({ id: 'laughing-face', label: 'Smiech', category: 'people', codepoint: '1f606', legacyGlyph: '\u{1F606}' }),
  buildAsset({ id: 'grin-sweat', label: 'Usmiech-z-potem', category: 'people', codepoint: '1f605', legacyGlyph: '\u{1F605}' }),
  buildAsset({ id: 'joy-face', label: 'Beksa-ze-smiechu', category: 'people', codepoint: '1f602', legacyGlyph: '\u{1F602}' }),
  buildAsset({ id: 'rofl', label: 'Turla-sie-ze-smiechu', category: 'people', codepoint: '1f923', legacyGlyph: '\u{1F923}' }),
  buildAsset({ id: 'loudly-crying', label: 'Placze-glosno', category: 'people', codepoint: '1f62d', legacyGlyph: '\u{1F62D}' }),
  buildAsset({ id: 'wink-face', label: 'Perskie-oko', category: 'people', codepoint: '1f609', legacyGlyph: '\u{1F609}' }),
  buildAsset({ id: 'kissing', label: 'Buzka', category: 'people', codepoint: '1f617', legacyGlyph: '\u{1F617}' }),
  buildAsset({ id: 'kissing-smiling-eyes', label: 'Buzka-z-przymruzonymi-oczami', category: 'people', codepoint: '1f619', legacyGlyph: '\u{1F619}' }),
  buildAsset({ id: 'kissing-closed-eyes', label: 'Buzka-z-zamknietymi-oczami', category: 'people', codepoint: '1f61a', legacyGlyph: '\u{1F61A}' }),
  buildAsset({ id: 'kissing-face', label: 'Calus', category: 'people', codepoint: '1f618', legacyGlyph: '\u{1F618}' }),
  buildAsset({ id: 'smiling-hearts', label: 'Rozczulony', category: 'people', codepoint: '1f970', legacyGlyph: '\u{1F970}' }),
  buildAsset({ id: 'heart-eyes', label: 'Zauroczony', category: 'people', codepoint: '1f60d', legacyGlyph: '\u{1F60D}' }),
  buildAsset({ id: 'star-struck', label: 'Zachwyt', category: 'people', codepoint: '1f929', legacyGlyph: '\u{1F929}' }),
  buildAsset({ id: 'partying-face', label: 'Imprezka', category: 'people', codepoint: '1f973', legacyGlyph: '\u{1F973}' }),
  buildAsset({ id: 'melting-face', label: 'Rozplywa-sie', category: 'people', codepoint: '1fae0', legacyGlyph: '\u{1FAE0}' }),
  buildAsset({ id: 'upside-down-face', label: 'Do-gory-nogami', category: 'people', codepoint: '1f643', legacyGlyph: '\u{1F643}' }),
  buildAsset({ id: 'slightly-happy', label: 'Lekki-usmiech', category: 'people', codepoint: '1f642', legacyGlyph: '\u{1F642}' }),
  buildAsset({ id: 'happy-cry', label: 'Usmiech-przez-lzy', category: 'people', codepoint: '1f972', legacyGlyph: '\u{1F972}' }),
  buildAsset({ id: 'holding-back-tears', label: 'Powstrzymuje-lzy', category: 'people', codepoint: '1f979', legacyGlyph: '\u{1F979}' }),
  buildAsset({ id: 'blush', label: 'Rumieniec', category: 'people', codepoint: '1f60a', legacyGlyph: '\u{1F60A}' }),
  buildAsset({ id: 'relieved', label: 'Ulga', category: 'people', codepoint: '1f60c', legacyGlyph: '\u{1F60C}' }),
  buildAsset({ id: 'smirk', label: 'Usmieszek', category: 'people', codepoint: '1f60f', legacyGlyph: '\u{1F60F}' }),
  buildAsset({ id: 'drool', label: 'Slinotok', category: 'people', codepoint: '1f924', legacyGlyph: '\u{1F924}' }),
  buildAsset({ id: 'yum', label: 'Mniam', category: 'people', codepoint: '1f60b', legacyGlyph: '\u{1F60B}' }),
  buildAsset({ id: 'stuck-out-tongue', label: 'Pokazuje-jezyk', category: 'people', codepoint: '1f61b', legacyGlyph: '\u{1F61B}' }),
  buildAsset({ id: 'squinting-tongue', label: 'Jezyk-z-przymruzeniem', category: 'people', codepoint: '1f61d', legacyGlyph: '\u{1F61D}' }),
  buildAsset({ id: 'tongue-face', label: 'Zartownis', category: 'people', codepoint: '1f61c', legacyGlyph: '\u{1F61C}' }),
  buildAsset({ id: 'zany-face', label: 'Wariat', category: 'people', codepoint: '1f92a', legacyGlyph: '\u{1F92A}' }),
  buildAsset({ id: 'woozy-face', label: 'Zamroczony', category: 'people', codepoint: '1f974', legacyGlyph: '\u{1F974}' }),
  buildAsset({ id: 'pensive', label: 'Zadumany', category: 'people', codepoint: '1f614', legacyGlyph: '\u{1F614}' }),
  buildAsset({ id: 'pleading', label: 'Proszacy', category: 'people', codepoint: '1f97a', legacyGlyph: '\u{1F97A}' }),
  buildAsset({ id: 'grimacing', label: 'Skrzywiony-usmiech', category: 'people', codepoint: '1f62c', legacyGlyph: '\u{1F62C}' }),
  buildAsset({ id: 'expressionless', label: 'Bez-wyrazu', category: 'people', codepoint: '1f611', legacyGlyph: '\u{1F611}' }),
  buildAsset({ id: 'neutral-face', label: 'Neutralny', category: 'people', codepoint: '1f610', legacyGlyph: '\u{1F610}' }),
  buildAsset({ id: 'mouth-none', label: 'Bez-ust', category: 'people', codepoint: '1f636', legacyGlyph: '\u{1F636}' }),
  buildAsset({ id: 'dotted-line-face', label: 'Kropkowana-twarz', category: 'people', codepoint: '1fae5', legacyGlyph: '\u{1FAE5}' }),
  buildAsset({ id: 'zipper-face', label: 'Zamek-na-ustach', category: 'people', codepoint: '1f910', legacyGlyph: '\u{1F910}' }),
  buildAsset({ id: 'salute', label: 'Salutuje', category: 'people', codepoint: '1fae1', legacyGlyph: '\u{1FAE1}' }),
  buildAsset({ id: 'thinking-face', label: 'Mysliciel', category: 'people', codepoint: '1f914', legacyGlyph: '\u{1F914}' }),
  buildAsset({ id: 'shushing-face', label: 'Ciii', category: 'people', codepoint: '1f92b', legacyGlyph: '\u{1F92B}' }),
  buildAsset({ id: 'hand-over-mouth', label: 'Dlon-na-ustach', category: 'people', codepoint: '1f92d', legacyGlyph: '\u{1F92D}' }),
  buildAsset({ id: 'smiling-eyes-hand-over-mouth', label: 'Zakryty-usmiech', category: 'people', codepoint: '1fae2', legacyGlyph: '\u{1FAE2}' }),
  buildAsset({ id: 'yawn', label: 'Ziewa', category: 'people', codepoint: '1f971', legacyGlyph: '\u{1F971}' }),
  buildAsset({ id: 'hug-face', label: 'Przytulas', category: 'people', codepoint: '1f917', legacyGlyph: '\u{1F917}' }),
  buildAsset({ id: 'peeking', label: 'Podejrzenie', category: 'people', codepoint: '1fae3', legacyGlyph: '\u{1FAE3}' }),
  buildAsset({ id: 'screaming', label: 'Krzyk', category: 'people', codepoint: '1f631', legacyGlyph: '\u{1F631}' }),
  buildAsset({ id: 'raised-eyebrow', label: 'Uniesiona-brew', category: 'people', codepoint: '1f928', legacyGlyph: '\u{1F928}' }),
  buildAsset({ id: 'monocle-face', label: 'Monokl', category: 'people', codepoint: '1f9d0', legacyGlyph: '\u{1F9D0}' }),
  buildAsset({ id: 'unamused', label: 'Niezadowolony', category: 'people', codepoint: '1f612', legacyGlyph: '\u{1F612}' }),
  buildAsset({ id: 'rolling-eyes', label: 'Przewraca-oczami', category: 'people', codepoint: '1f644', legacyGlyph: '\u{1F644}' }),
  buildAsset({ id: 'triumph', label: 'Tryumf', category: 'people', codepoint: '1f624', legacyGlyph: '\u{1F624}' }),
  buildAsset({ id: 'angry', label: 'Zly', category: 'people', codepoint: '1f620', legacyGlyph: '\u{1F620}' }),
  buildAsset({ id: 'rage', label: 'Wsciekly', category: 'people', codepoint: '1f621', legacyGlyph: '\u{1F621}' }),
  buildAsset({ id: 'cursing', label: 'Przeklina', category: 'people', codepoint: '1f92c', legacyGlyph: '\u{1F92C}' }),
  buildAsset({ id: 'sad', label: 'Smutny', category: 'people', codepoint: '1f61e', legacyGlyph: '\u{1F61E}' }),
  buildAsset({ id: 'sweat', label: 'Spiety', category: 'people', codepoint: '1f613', legacyGlyph: '\u{1F613}' }),
  buildAsset({ id: 'worried', label: 'Zmartwiony', category: 'people', codepoint: '1f61f', legacyGlyph: '\u{1F61F}' }),
  buildAsset({ id: 'concerned', label: 'Zaniepokojony', category: 'people', codepoint: '1f625', legacyGlyph: '\u{1F625}' }),
  buildAsset({ id: 'cry', label: 'Placze', category: 'people', codepoint: '1f622', legacyGlyph: '\u{1F622}' }),
  buildAsset({ id: 'frown', label: 'Przygnebiony', category: 'people', codepoint: '1f641', legacyGlyph: '\u{1F641}' }),
  buildAsset({ id: 'diagonal-mouth', label: 'Krzywe-usta', category: 'people', codepoint: '1fae4', legacyGlyph: '\u{1FAE4}' }),
  buildAsset({ id: 'anxious-with-sweat', label: 'Strach-z-potem', category: 'people', codepoint: '1f630', legacyGlyph: '\u{1F630}' }),
  buildAsset({ id: 'scared', label: 'Przestraszony', category: 'people', codepoint: '1f628', legacyGlyph: '\u{1F628}' }),
  buildAsset({ id: 'anguished', label: 'Udretczony', category: 'people', codepoint: '1f627', legacyGlyph: '\u{1F627}' }),
  buildAsset({ id: 'gasp', label: 'Oho', category: 'people', codepoint: '1f62e', legacyGlyph: '\u{1F62E}' }),
  buildAsset({ id: 'mouth-open', label: 'Otwarte-usta', category: 'people', codepoint: '1f62f', legacyGlyph: '\u{1F62F}' }),
  buildAsset({ id: 'surprised', label: 'Zaskoczony', category: 'people', codepoint: '1f632', legacyGlyph: '\u{1F632}' }),
  buildAsset({ id: 'astonished', label: 'Oszolomiony', category: 'people', codepoint: '1f633', legacyGlyph: '\u{1F633}' }),
  buildAsset({ id: 'flushed', label: 'Zarumieniony', category: 'people', codepoint: '1f633', legacyGlyph: '\u{1F633}' }),
  buildAsset({ id: 'mind-blown', label: 'Szok', category: 'people', codepoint: '1f92f', legacyGlyph: '\u{1F92F}' }),
  buildAsset({ id: 'scrunched-mouth', label: 'Skurczone-usta', category: 'people', codepoint: '1f616', legacyGlyph: '\u{1F616}' }),
  buildAsset({ id: 'scrunched-eyes', label: 'Skurczone-oczy', category: 'people', codepoint: '1f623', legacyGlyph: '\u{1F623}' }),
  buildAsset({ id: 'weary', label: 'Wyczerpany', category: 'people', codepoint: '1f629', legacyGlyph: '\u{1F629}' }),
  buildAsset({ id: 'distraught', label: 'Roztrzesiony', category: 'people', codepoint: '1f62b', legacyGlyph: '\u{1F62B}' }),
  buildAsset({ id: 'x-eyes', label: 'Ikonki-w-oczach', category: 'people', codepoint: '1f635', legacyGlyph: '\u{1F635}' }),
  buildAsset({ id: 'dizzy-face', label: 'Kreci-sie-w-glowie', category: 'people', codepoint: '1f974', legacyGlyph: '\u{1F974}' }),
  buildAsset({ id: 'shaking-face', label: 'Trzesie-sie', category: 'people', codepoint: '1fae8', legacyGlyph: '\u{1FAE8}' }),
  buildAsset({ id: 'cold-face', label: 'Zimno', category: 'people', codepoint: '1f976', legacyGlyph: '\u{1F976}' }),
  buildAsset({ id: 'hot-face', label: 'Goraco', category: 'people', codepoint: '1f975', legacyGlyph: '\u{1F975}' }),
  buildAsset({ id: 'sick', label: 'Chory', category: 'people', codepoint: '1f922', legacyGlyph: '\u{1F922}' }),
  buildAsset({ id: 'vomit', label: 'Wymiotuje', category: 'people', codepoint: '1f92e', legacyGlyph: '\u{1F92E}' }),
  buildAsset({ id: 'sleep', label: 'Spi', category: 'people', codepoint: '1f634', legacyGlyph: '\u{1F634}' }),
  buildAsset({ id: 'sleepy-face', label: 'Spiacy', category: 'people', codepoint: '1f62a', legacyGlyph: '\u{1F62A}' }),
  buildAsset({ id: 'sneeze', label: 'Kicha', category: 'people', codepoint: '1f927', legacyGlyph: '\u{1F927}' }),
  buildAsset({ id: 'thermometer-face', label: 'Termometr', category: 'people', codepoint: '1f912', legacyGlyph: '\u{1F912}' }),
  buildAsset({ id: 'bandage-face', label: 'Bandaż', category: 'people', codepoint: '1f915', legacyGlyph: '\u{1F915}' }),
  buildAsset({ id: 'mask', label: 'Maska', category: 'people', codepoint: '1f637', legacyGlyph: '\u{1F637}' }),
  buildAsset({ id: 'liar', label: 'Klamiaca-buzka', category: 'people', codepoint: '1f925', legacyGlyph: '\u{1F925}' }),
  buildAsset({ id: 'angel-face', label: 'Aniol', category: 'people', codepoint: '1f607', legacyGlyph: '\u{1F607}' }),
  buildAsset({ id: 'cowboy-face', label: 'Kowboj', category: 'people', codepoint: '1f920', legacyGlyph: '\u{1F920}' }),
  buildAsset({ id: 'money-face', label: 'Forsa', category: 'people', codepoint: '1f911', legacyGlyph: '\u{1F911}' }),
  buildAsset({ id: 'nerd-face', label: 'Madrala', category: 'people', codepoint: '1f913', legacyGlyph: '\u{1F913}' }),
  buildAsset({ id: 'sunglasses-face', label: 'Okulary', category: 'people', codepoint: '1f60e', legacyGlyph: '\u{1F60E}' }),
  buildAsset({ id: 'disguise', label: 'Przebranie', category: 'people', codepoint: '1f978', legacyGlyph: '\u{1F978}' }),
  buildAsset({ id: 'clown-face', label: 'Klaun', category: 'people', codepoint: '1f921', legacyGlyph: '\u{1F921}' }),
  buildAsset({ id: 'poop', label: 'Glupek', category: 'people', codepoint: '1f4a9', legacyGlyph: '\u{1F4A9}' }),
  buildAsset({ id: 'imp-smile', label: 'Diabelek-usmiech', category: 'people', codepoint: '1f608', legacyGlyph: '\u{1F608}' }),
  buildAsset({ id: 'imp-frown', label: 'Diabelek-zlosc', category: 'people', codepoint: '1f47f', legacyGlyph: '\u{1F47F}' }),
  buildAsset({ id: 'ghost', label: 'Duszek', category: 'people', codepoint: '1f47b', legacyGlyph: '\u{1F47B}' }),
  buildAsset({ id: 'skull', label: 'Czaszka', category: 'people', codepoint: '1f480', legacyGlyph: '\u{1F480}' }),
  buildAsset({ id: 'snowman', label: 'Balwan', category: 'people', codepoint: '26c4', legacyGlyph: '\u{26C4}' }),
  buildAsset({ id: 'jack-o-lantern', label: 'Dynia', category: 'people', codepoint: '1f383', legacyGlyph: '\u{1F383}' }),
  buildAsset({ id: 'robot-face', label: 'Robot', category: 'people', codepoint: '1f916', legacyGlyph: '\u{1F916}' }),
  buildAsset({ id: 'alien', label: 'Kosmita', category: 'people', codepoint: '1f47d', legacyGlyph: '\u{1F47D}' }),
  buildAsset({ id: 'alien-monster', label: 'Kosmita-arcade', category: 'people', codepoint: '1f47e', legacyGlyph: '\u{1F47E}' }),
  buildAsset({ id: 'sun-with-face', label: 'Slonce-z-buzka', category: 'people', codepoint: '1f31e', legacyGlyph: '\u{1F31E}' }),
  buildAsset({ id: 'moon-face-first-quarter', label: 'Ksiezyc-pierwsza-kwadra', category: 'people', codepoint: '1f31b', legacyGlyph: '\u{1F31B}' }),
  buildAsset({ id: 'moon-face-last-quarter', label: 'Ksiezyc-ostatnia-kwadra', category: 'people', codepoint: '1f31c', legacyGlyph: '\u{1F31C}' }),
  buildAsset({ id: 'smiley-cat', label: 'Zadowolony-kot', category: 'people', codepoint: '1f63a', legacyGlyph: '\u{1F63A}' }),
  buildAsset({ id: 'smile-cat', label: 'Koci-usmiech', category: 'people', codepoint: '1f638', legacyGlyph: '\u{1F638}' }),
  buildAsset({ id: 'joy-cat', label: 'Kot-lzy-smiechu', category: 'people', codepoint: '1f639', legacyGlyph: '\u{1F639}' }),
  buildAsset({ id: 'heart-eyes-cat', label: 'Kot-z-serduszkami', category: 'people', codepoint: '1f63b', legacyGlyph: '\u{1F63B}' }),
  buildAsset({ id: 'smirk-cat', label: 'Sprytny-kot', category: 'people', codepoint: '1f63c', legacyGlyph: '\u{1F63C}' }),
  buildAsset({ id: 'kissing-cat', label: 'Calujacy-kot', category: 'people', codepoint: '1f63d', legacyGlyph: '\u{1F63D}' }),
  buildAsset({ id: 'scream-cat', label: 'Przerazony-kot', category: 'people', codepoint: '1f640', legacyGlyph: '\u{1F640}' }),
  buildAsset({ id: 'crying-cat-face', label: 'Placzący-kot', category: 'people', codepoint: '1f63f', legacyGlyph: '\u{1F63F}' }),
  buildAsset({ id: 'pouting-cat', label: 'Nadety-kot', category: 'people', codepoint: '1f63e', legacyGlyph: '\u{1F63E}' }),
  buildAsset({ id: 'see-no-evil', label: 'Nie-widze', category: 'people', codepoint: '1f648', legacyGlyph: '\u{1F648}' }),
  buildAsset({ id: 'hear-no-evil', label: 'Nie-slysze', category: 'people', codepoint: '1f649', legacyGlyph: '\u{1F649}' }),
  buildAsset({ id: 'speak-no-evil', label: 'Nie-mowie', category: 'people', codepoint: '1f64a', legacyGlyph: '\u{1F64A}' }),
  buildAsset({ id: 'cow-face', label: 'Krowa', category: 'animals', codepoint: '1f42e', legacyGlyph: '\u{1F42E}' }),
  buildAsset({ id: 'unicorn', label: 'Jednorozec', category: 'animals', codepoint: '1f984', legacyGlyph: '\u{1F984}' }),
  buildAsset({ id: 'lizard', label: 'Jaszczurka', category: 'animals', codepoint: '1f98e', legacyGlyph: '\u{1F98E}' }),
  buildAsset({ id: 'dragon', label: 'Smok', category: 'animals', codepoint: '1f409', legacyGlyph: '\u{1F409}' }),
  buildAsset({ id: 't-rex', label: 'T-rex', category: 'animals', codepoint: '1f996', legacyGlyph: '\u{1F996}' }),
  buildAsset({ id: 'dinosaur', label: 'Dinozaur', category: 'animals', codepoint: '1f995', legacyGlyph: '\u{1F995}' }),
  buildAsset({ id: 'turtle', label: 'Zolw', category: 'animals', codepoint: '1f422', legacyGlyph: '\u{1F422}' }),
  buildAsset({ id: 'crocodile', label: 'Krokodyl', category: 'animals', codepoint: '1f40a', legacyGlyph: '\u{1F40A}' }),
  buildAsset({ id: 'snake', label: 'Waz', category: 'animals', codepoint: '1f40d', legacyGlyph: '\u{1F40D}' }),
  buildAsset({ id: 'frog', label: 'Zaba', category: 'animals', codepoint: '1f438', legacyGlyph: '\u{1F438}' }),
  buildAsset({ id: 'rabbit', label: 'Krolik', category: 'animals', codepoint: '1f407', legacyGlyph: '\u{1F407}' }),
  buildAsset({ id: 'rat', label: 'Szczur', category: 'animals', codepoint: '1f400', legacyGlyph: '\u{1F400}' }),
  buildAsset({ id: 'poodle', label: 'Pudel', category: 'animals', codepoint: '1f429', legacyGlyph: '\u{1F429}' }),
  buildAsset({ id: 'dog', label: 'Pies', category: 'animals', codepoint: '1f436', legacyGlyph: '\u{1F436}' }),
  buildAsset({ id: 'guide-dog', label: 'Pies-przewodnik', category: 'animals', codepoint: '1f9ae', legacyGlyph: '\u{1F9AE}' }),
  buildAsset({ id: 'pig', label: 'Swinia', category: 'animals', codepoint: '1f416', legacyGlyph: '\u{1F416}' }),
  buildAsset({ id: 'racehorse', label: 'Kon', category: 'animals', codepoint: '1f40e', legacyGlyph: '\u{1F40E}' }),
  buildAsset({ id: 'donkey', label: 'Osiol', category: 'animals', codepoint: '1facf', legacyGlyph: '\u{1FACF}' }),
  buildAsset({ id: 'ox', label: 'Wol', category: 'animals', codepoint: '1f402', legacyGlyph: '\u{1F402}' }),
  buildAsset({ id: 'goat', label: 'Koza', category: 'animals', codepoint: '1f410', legacyGlyph: '\u{1F410}' }),
  buildAsset({ id: 'kangaroo', label: 'Kangur', category: 'animals', codepoint: '1f998', legacyGlyph: '\u{1F998}' }),
  buildAsset({ id: 'tiger', label: 'Tygrys', category: 'animals', codepoint: '1f405', legacyGlyph: '\u{1F405}' }),
  buildAsset({ id: 'monkey', label: 'Malpa', category: 'animals', codepoint: '1f412', legacyGlyph: '\u{1F412}' }),
  buildAsset({ id: 'gorilla', label: 'Goryl', category: 'animals', codepoint: '1f98d', legacyGlyph: '\u{1F98D}' }),
  buildAsset({ id: 'orangutan', label: 'Orangutan', category: 'animals', codepoint: '1f9a7', legacyGlyph: '\u{1F9A7}' }),
  buildAsset({ id: 'chipmunk', label: 'Wiewiorka', category: 'animals', codepoint: '1f43f', legacyGlyph: '\u{1F43F}' }),
  buildAsset({ id: 'otter', label: 'Wydra', category: 'animals', codepoint: '1f9a6', legacyGlyph: '\u{1F9A6}' }),
  buildAsset({ id: 'bat', label: 'Nietoperz', category: 'animals', codepoint: '1f987', legacyGlyph: '\u{1F987}' }),
  buildAsset({ id: 'bird', label: 'Ptak', category: 'animals', codepoint: '1f426', legacyGlyph: '\u{1F426}' }),
  buildAsset({ id: 'rooster', label: 'Kogut', category: 'animals', codepoint: '1f413', legacyGlyph: '\u{1F413}' }),
  buildAsset({ id: 'hatching-chick', label: 'Pisklak-w-skorupce', category: 'animals', codepoint: '1f423', legacyGlyph: '\u{1F423}' }),
  buildAsset({ id: 'baby-chick', label: 'Pisklak', category: 'animals', codepoint: '1f424', legacyGlyph: '\u{1F424}' }),
  buildAsset({ id: 'hatched-chick', label: 'Kurczaczek', category: 'animals', codepoint: '1f425', legacyGlyph: '\u{1F425}' }),
  buildAsset({ id: 'eagle', label: 'Orzel', category: 'animals', codepoint: '1f985', legacyGlyph: '\u{1F985}' }),
  buildAsset({ id: 'owl', label: 'Sowa', category: 'animals', codepoint: '1f989', legacyGlyph: '\u{1F989}' }),
  buildAsset({ id: 'peace-dove', label: 'Golab', category: 'animals', codepoint: '1f54a', legacyGlyph: '\u{1F54A}' }),
  buildAsset({ id: 'goose', label: 'Ges', category: 'animals', codepoint: '1fabf', legacyGlyph: '\u{1FABF}' }),
  buildAsset({ id: 'peacock', label: 'Paw', category: 'animals', codepoint: '1f99a', legacyGlyph: '\u{1F99A}' }),
  buildAsset({ id: 'seal', label: 'Foka', category: 'animals', codepoint: '1f9ad', legacyGlyph: '\u{1F9AD}' }),
  buildAsset({ id: 'shark', label: 'Rekin', category: 'animals', codepoint: '1f988', legacyGlyph: '\u{1F988}' }),
  buildAsset({ id: 'dolphin', label: 'Delfin', category: 'animals', codepoint: '1f42c', legacyGlyph: '\u{1F42C}' }),
  buildAsset({ id: 'whale', label: 'Wieloryb', category: 'animals', codepoint: '1f433', legacyGlyph: '\u{1F433}' }),
  buildAsset({ id: 'fish', label: 'Ryba', category: 'animals', codepoint: '1f41f', legacyGlyph: '\u{1F41F}' }),
  buildAsset({ id: 'blowfish', label: 'Rozdymka', category: 'animals', codepoint: '1f421', legacyGlyph: '\u{1F421}' }),
  buildAsset({ id: 'lobster', label: 'Homar', category: 'animals', codepoint: '1f99e', legacyGlyph: '\u{1F99E}' }),
  buildAsset({ id: 'crab', label: 'Krab', category: 'animals', codepoint: '1f980', legacyGlyph: '\u{1F980}' }),
  buildAsset({ id: 'octopus', label: 'Osmiornica', category: 'animals', codepoint: '1f419', legacyGlyph: '\u{1F419}' }),
  buildAsset({ id: 'jellyfish', label: 'Meduza', category: 'animals', codepoint: '1fabc', legacyGlyph: '\u{1FABC}' }),
  buildAsset({ id: 'scorpion', label: 'Skorpion', category: 'animals', codepoint: '1f982', legacyGlyph: '\u{1F982}' }),
  buildAsset({ id: 'spider', label: 'Pajak', category: 'animals', codepoint: '1f577', legacyGlyph: '\u{1F577}' }),
  buildAsset({ id: 'snail', label: 'Slimak', category: 'animals', codepoint: '1f40c', legacyGlyph: '\u{1F40C}' }),
  buildAsset({ id: 'ant', label: 'Mrowka', category: 'animals', codepoint: '1f41c', legacyGlyph: '\u{1F41C}' }),
  buildAsset({ id: 'mosquito', label: 'Komar', category: 'animals', codepoint: '1f99f', legacyGlyph: '\u{1F99F}' }),
  buildAsset({ id: 'cockroach', label: 'Karaluch', category: 'animals', codepoint: '1fab3', legacyGlyph: '\u{1FAB3}' }),
  buildAsset({ id: 'fly', label: 'Mucha', category: 'animals', codepoint: '1fab0', legacyGlyph: '\u{1FAB0}' }),
  buildAsset({ id: 'bee', label: 'Pszczola', category: 'animals', codepoint: '1f41d', legacyGlyph: '\u{1F41D}' }),
  buildAsset({ id: 'lady-bug', label: 'Biedronka', category: 'animals', codepoint: '1f41e', legacyGlyph: '\u{1F41E}' }),
  buildAsset({ id: 'butterfly', label: 'Motyl', category: 'animals', codepoint: '1f98b', legacyGlyph: '\u{1F98B}' }),
  buildAsset({ id: 'bug', label: 'Gasienica', category: 'animals', codepoint: '1f41b', legacyGlyph: '\u{1F41B}' }),
  buildAsset({ id: 'worm', label: 'Robak', category: 'animals', codepoint: '1fab1', legacyGlyph: '\u{1FAB1}' }),
  buildAsset({ id: 'theater', label: 'Maski', category: 'other', codepoint: '1f3ad', legacyGlyph: '\u{1F3AD}' }),
  buildAsset({ id: 'circus', label: 'Blask', category: 'other', codepoint: '1f31f', legacyGlyph: '\u{1F31F}' }),
  buildAsset({ id: 'palette', label: 'Tecza', category: 'other', codepoint: '1f308', legacyGlyph: '\u{1F308}' }),
  buildAsset({ id: 'clapper', label: 'Klapser', category: 'other', codepoint: '1f3ac', legacyGlyph: '\u{1F3AC}' }),
  buildAsset({ id: 'microphone', label: 'Trabka', category: 'other', codepoint: '1f3ba', legacyGlyph: '\u{1F3BA}' }),
  buildAsset({ id: 'guitar', label: 'Gitara', category: 'other', codepoint: '1f3b8', legacyGlyph: '\u{1F3B8}' }),
  buildAsset({ id: 'dart', label: 'Rzutki', category: 'other', codepoint: '1f3af', legacyGlyph: '\u{1F3AF}' }),
  buildAsset({ id: 'trophy', label: 'Trofeum', category: 'other', codepoint: '1f3c6', legacyGlyph: '\u{1F3C6}' }),
  buildAsset({ id: 'star', label: 'Gwiazda', category: 'other', codepoint: '2b50', legacyGlyph: '\u{2B50}' }),
  buildAsset({ id: 'fire', label: 'Ognien', category: 'other', codepoint: '1f525', legacyGlyph: '\u{1F525}' }),
  buildAsset({ id: 'gem', label: 'Klejnot', category: 'other', codepoint: '1f48e', legacyGlyph: '\u{1F48E}' }),
  buildAsset({ id: 'rocket', label: 'Rakieta', category: 'other', codepoint: '1f680', legacyGlyph: '\u{1F680}' }),
  buildAsset({ id: 'lightning', label: 'Piorun', category: 'other', codepoint: '26a1', legacyGlyph: '\u{26A1}' }),
  buildAsset({ id: 'soccer-ball', label: 'Pilka', category: 'other', codepoint: '26bd', legacyGlyph: '\u{26BD}' }),
  buildAsset({ id: 'dice', label: 'Kostka', category: 'other', codepoint: '1f3b2', legacyGlyph: '\u{1F3B2}' }),
  buildAsset({ id: 'crown', label: 'Korona', category: 'other', codepoint: '1f451', legacyGlyph: '\u{1F451}' }),
  buildAsset({ id: 'headphones', label: 'Saksofon', category: 'other', codepoint: '1f3b7', legacyGlyph: '\u{1F3B7}' }),
  buildAsset({ id: 'basketball', label: 'Kosz', category: 'other', codepoint: '1f3c0', legacyGlyph: '\u{1F3C0}' }),
  buildAsset({ id: 'volleyball', label: 'Beben', category: 'other', codepoint: '1f941', legacyGlyph: '\u{1F941}' }),
  buildAsset({ id: 'gamepad', label: 'Laptop', category: 'other', codepoint: '1f4bb', legacyGlyph: '\u{1F4BB}' }),
  buildAsset({ id: 'joystick', label: 'Telewizor', category: 'other', codepoint: '1f4fa', legacyGlyph: '\u{1F4FA}' }),
  buildAsset({ id: 'camera', label: 'Kamera-filmowa', category: 'other', codepoint: '1f3a5', legacyGlyph: '\u{1F3A5}' }),
  buildAsset({ id: 'movie-camera', label: 'Kamera', category: 'other', codepoint: '1f3a5', legacyGlyph: '\u{1F3A5}' }),
  buildAsset({ id: 'books', label: 'Ksiazki', category: 'other', codepoint: '1f4da', legacyGlyph: '\u{1F4DA}' }),
  buildAsset({ id: 'magic-wand', label: 'Rozdzka', category: 'other', codepoint: '1fa84', legacyGlyph: '\u{1FA84}' }),
  buildAsset({ id: 'saturn', label: 'Saturn', category: 'other', codepoint: '1fa90', legacyGlyph: '\u{1FA90}' }),
  buildAsset({ id: 'crystal-ball', label: 'Kula', category: 'other', codepoint: '1f52e', legacyGlyph: '\u{1F52E}' }),
] as const
