export const plus18Words: string[] = [
  'kochanek', 'alkohol', 'hazard', 'plotka', 'skandal', 'zemsta', 'intryga',
  'szpieg', 'tajemnica', 'zbrodnia', 'zdrada', 'uwodzenie', 'przekupstwo',
  'korupcja', 'ekstaza', 'obsesja', 'kult', 'prześladowanie', 'manipulacja',
  'dominacja', 'transgresja', 'chaos', 'anarchia', 'dewiacja', 'prowokacja',
  'tabu', 'grzech', 'pożądanie', 'namiętność', 'niemoralność', 'romans',
  'flirt', 'pokusa', 'afera', 'szantaż', 'kasyno', 'perfumy', 'żądza',
  'nagość', 'alkowa', 'dealer', 'występek', 'nocleg', 'szept', 'zazdrość',
  'układ', 'koktajl', 'randka', 'balanga', 'fetysz', 'ruletka', 'burdel',
  'libido', 'vip', 'sekret', 'ukrywka', 'amant', 'kochanka', 'sugestia',
  'gorset', 'bielizna', 'noc', 'after', 'clubbing', 'toast', 'bar',
  'upojenie', 'rumieniec', 'dotyk', 'odurzenie', 'kokaina', 'dym', 'cygaro',
  'rozpusta', 'demoralizacja', 'niegrzeczność', 'wyuzdanie', 'podryw',
  'przygoda', 'ukojenie', 'dramat', 'serenada', 'zakład', 'przekręt',
  'gang', 'przemyt', 'hucpa', 'noclegownia', 'żart', 'pikanteria',
  'kuszenie', 'rozterka', 'niedyskrecja', 'kompromitacja', 'poker',
  'ekshibicjonizm', 'zmysłowość', 'upadek', 'afrodyzjak', 'orgietka',
]
