export const plus18Words: string[] = [
  'kochanek', 'alkohol', 'hazard', 'plotka', 'skandal', 'zemsta', 'intryga', 'szpieg',
  'tajemnica', 'zbrodnia', 'zdrada', 'uwodzenie', 'przekupstwo', 'korupcja', 'ekstaza', 'obsesja',
  'kult', 'prześladowanie', 'manipulacja', 'dominacja', 'transgresja', 'chaos', 'anarchia', 'dewiacja',
  'prowokacja', 'tabu', 'grzech', 'pożądanie', 'namiętność', 'niemoralność', 'romans', 'flirt',
  'pokusa', 'afera', 'szantaż', 'kasyno', 'perfumy', 'żądza', 'nagość',
  'dealer', 'występek', 'stosunek', 'stękanie', 'zazdrość', 'schadzka', 'koktajl', 'randka',
  'balanga', 'fetysz', 'ruletka', 'burdel', 'libido', 'sekret', 'melina',
  'amant', 'kochanka', 'sugestia', 'gorset', 'bielizna', 'noc', 'afterek',
  'lodzik', 'bar', 'upojenie', 'rumieniec', 'dotyk', 'odurzenie', 'kokaina', 'dym',
  'cygaro', 'rozpusta', 'demoralizacja', 'niegrzeczność', 'wyuzdanie', 'podryw', 'przygoda', 'pragnienie',
  'pościel', 'zakład', 'przekręt', 'gang', 'przemyt', 'zbliżenie',
  'pikanteria', 'kuszenie', 'rozterka', 'niedyskrecja', 'kompromitacja', 'poker', 'zmysłowość',
  'upadek', 'afrodyzjak', 'orgia', 'porno', 'seks', 'podniecenie', 'orgazm', 'sperma',
  'wytrysk', 'spust', 'penis', 'kutas', 'fiut', 'pała', 'cipka', 'pizda',
  'pochwa', 'łechtaczka', 'dupa', 'tyłek', 'cycki', 'biust', 'sutek', 'krocze',
  'oddech', 'ślina', 'jęk', 'dreszcz', 'usta', 'język', 'szyja', 'mokro',
  'ostro', 'zalać', 'laska', 'obciągnie', 'mineta',
  'creampie', 'cumshot', 'anal', 'korek', 'palcówka', 'dziurka', 'muszelka',
  'bdsm', 'uległość', 'klaps', 'pejcz', 'bat', 'duszenie', 'podduszanie', 'knebel',
  'maska', 'obroża', 'smycz', 'krępowanie', 'kajdanki', 'lateks',
  'onlyfans', 'nudesy', 'dickpic', 'wyciek', 'sexting', 'tinder', 'stringi', 'koronka',
  'wibrator', 'dildo', 'zabawka', 'lubrykant', 'kondom', 'prezerwatywa', 'sexshop', 'trójkąt',
  'klub', 'dymanko', 'bzykanie', 'zaliczenie', 'banan', 'ogórek', 'kiełbasa',
  'parówka', 'melon', 'brzoskwinia', 'truskawka', 'śmietanka', 'lizak', 'ciastko', 'pączek',
  'sos', 'krem', 'rurka', 'drążek', 'pilot', 'ładowarka', 'kabel', 'wibracja',
  'pompka', 'tłok', 'dysza', 'butelka', 'otwieracz', 'gumka', 'taśma', 'pasek',
  'knot', 'śruba', 'wkręt', 'pończochy', 'stanik', 'dekolt', 'obcasy', 'szpilki',
  'skóra', 'garnitur', 'mundurek', 'makijaż', 'szminka', 'tatuaż', 'kolczyk', 'dezodorant',
  'łazienka', 'prysznic', 'wanna', 'hotel', 'pokój', 'łóżko', 'poduszka', 'kołdra',
  'zasłona', 'ciemność', 'zaloty', 'spojrzenie', 'zaczepka', 'komplement', 'iskra', 'napięcie',
  'chemia', 'grzeszek', 'zakaz', 'rywal', 'crush', 'ex', 'ghosting', 'match',
  'priv', 'wiadomość', 'screenshot', 'blokada', 'igraszki', 'napalenie', 'rozwiązłość', 'wstyd',
  'impreza', 'melanż', 'karaoke', 'shot', 'drink', 'wódka', 'wino', 'whisky',
  'gin', 'rum', 'piwo', 'kac', 'toaleta', 'szatnia', 'perwersja', 'erotyka',
  'świntuszenie', 'kibel', 'erekcja', 'wzwód', 'pośladki', 'jaja', 'pieszczoty', 'całowanie',
  'obmacywanie', 'fantazja', 'pozycja', 'kamasutra', 'striptiz', 'sponsoring',
  'sponsor', 'sponsorka', 'swingers', 'podglądacz', 'roleplay', 'przebieranki', 'kabaretki',
  'podwiązka', 'rajstopy', 'bokserki', 'body', 'bustier', 'szlafrok', 'jacuzzi', 'sauna',
  'motel', 'apartament', 'backstage', 'viproom', 'loża', 'ciemnia', 'barman', 'barmanka',
  'numerek', 'jednorazówka', 'friendzone', 'układzik', 'osaczanie', 'zwodzenie', 'rezerwa',
  'stalker', 'redflag', 'greenflag', 'dyskrecja', 'afiszowanie', 'badoo', 'nudes',
  'afterparty', 'amfetamina', 'mdma', 'molly', 'zioło', 'skręt', 'joint', 'bongo',
  'lufka', 'prochy', 'trip', 'haj', 'zgon', 'upalenie', 'submisja',
  'uległy', 'władcza', 'niegrzeczny', 'niegrzeczna', 'zakazany', 'kuszący', 'gorączka', 'czułość',
  'petting', 'sekstape', 'sypialnia', 'masturbacja', 'onanizm', 'obnażanie', 'rozkosz', 'macanko',
  'podglądanie', 'rozbieranka', 'grzeszność', 'seksapil', 'frywolność', 'bezwstyd', 'lubieżność',
  'grupówka', 'roznegliż',
]
