export const standardWords: string[] = [
  'most', 'zamek', 'klucz', 'bank', 'wiatr', 'ocean', 'księżyc', 'ogień',
  'cień', 'skarb', 'burza', 'czas', 'statek', 'lew', 'drzewo', 'góra',
  'pająk', 'obłok', 'mapa', 'kompas', 'latarnia', 'struna', 'chmura',
  'liść', 'kamień', 'fala', 'nić', 'gwiazda', 'rzeka', 'wulkan', 'lustro',
  'ogród', 'słońce', 'deszcz', 'okno', 'fotel', 'wyspa', 'jaskinia',
  'pociąg', 'rower', 'dzwon', 'tarcza', 'miecz', 'lampa', 'piasek',
  'kruk', 'telefon', 'zegar', 'kwiat', 'magnes', 'jezioro', 'planetarium',
  'świeca', 'sokół', 'brama', 'papier', 'tulipan', 'młotek', 'szlak',
  'koperta', 'flet', 'studnia', 'wstęga', 'rakieta', 'zimno', 'płomień',
  'poranek', 'wieczór', 'wiosna', 'lato', 'jesień', 'zima', 'teatr',
  'kino', 'muzeum', 'boisko', 'warsztat', 'skrzynia', 'miód', 'pasieka',
  'ananas', 'cytryna', 'malina', 'jagoda', 'bałwan', 'śnieg', 'szron',
  'port', 'pomost', 'kotwica', 'siodło', 'balon', 'wir', 'echo', 'galeria',
  'szeptanka', 'melodia', 'korona', 'pagórek', 'tornado',
]
