export const CODENAMES_NAVIGATION_COMMANDS = {
  menuOpenSetup: 'codenames.menu.open-setup',
  menuOpenSettings: 'codenames.menu.open-settings',
  menuSelectRailTarget: 'codenames.menu.select-rail-target',
  settingsSelectCategory: 'codenames.settings.select-category',
  settingsStartBindingListen: 'codenames.settings.start-binding-listen',
  settingsResetBindings: 'codenames.settings.reset-bindings',
  settingsSaveBindings: 'codenames.settings.save-bindings',
  settingsExitToMenu: 'codenames.settings.exit-to-menu',
  setupClose: 'codenames.setup.close',
  setupStart: 'codenames.setup.start',
  runtimeRevealSelectedCard: 'codenames.runtime.reveal-selected-card',
  runtimeToggleStatusRail: 'codenames.runtime.toggle-status-rail',
  runtimeOpenSettings: 'codenames.runtime.open-settings',
  runtimeCloseSettings: 'codenames.runtime.close-settings',
  runtimeToggleSettingsSound: 'codenames.runtime.toggle-settings-sound',
  runtimeToggleSettingsAnimations: 'codenames.runtime.toggle-settings-animations',
  runtimeOpenSettingsExitConfirm: 'codenames.runtime.open-settings-exit-confirm',
  runtimeCancelSettingsExitConfirm: 'codenames.runtime.cancel-settings-exit-confirm',
  runtimeOpenResetConfirm: 'codenames.runtime.open-reset-confirm',
  runtimeCancelResetConfirm: 'codenames.runtime.cancel-reset-confirm',
  runtimeConfirmReset: 'codenames.runtime.confirm-reset',
  runtimeOpenBrowserExitAlert: 'codenames.runtime.open-browser-exit-alert',
  runtimeCloseBrowserExitAlert: 'codenames.runtime.close-browser-exit-alert',
  runtimeCloseStartBlocked: 'codenames.runtime.close-start-blocked',
  runtimeResetPoolAndRetry: 'codenames.runtime.reset-pool-and-retry',
  runtimeExitToMenu: 'codenames.runtime.exit-to-menu',
  runtimeStartGame: 'codenames.runtime.start-game',
  runtimeConfirmAssassinTeam: 'codenames.runtime.confirm-assassin-team',
} as const

export type CodenamesNavigationCommandId =
  typeof CODENAMES_NAVIGATION_COMMANDS[keyof typeof CODENAMES_NAVIGATION_COMMANDS]
