import type { WordCategory } from './index'

export const animals: WordCategory = {
  id: 'animals',
  name: 'Zwierzęta',
  wordsEasy: [
    'Pies',
    'Kot',
    'Słoń',
    'Żyrafa',
    'Pingwin',
    'Królik',
    'Chomik',
    'Papuga',
    'Kanarek',
    'Żółw',
    'Koń',
    'Krowa',
    'Świnia',
    'Owca',
    'Koza',
    'Kura',
    'Kogut',
    'Kaczka',
    'Gęś',
    'Indyk',
    'Ryba',
    'Rekin',
    'Delfin',
    'Wieloryb',
    'Foka',
    'Niedźwiedź',
    'Lis',
    'Wilk',
    'Jeż',
    'Wiewiórka',
    'Bóbr',
    'Mysz',
    'Szczur',
    'Zając',
    'Sarna',
    'Jeleń',
    'Łoś',
    'Dziki',
    'Kret',
    'Nietoperz',
    'Pszczoła',
    'Mrówka',
    'Biedronka',
    'Motyl',
    'Pająk',
    'Żaba',
    'Ropucha',
    'Wąż',
    'Jaszczurka',
    'Gołąb'
  ],
  wordsHard: [
    'Ornitorenk',
    'Kameleon',
    'Jeżozwierz',
    'Mrówkojad',
    'Ośmiornica',
    'Alpaka',
    'Lemur',
    'Manat',
    'Okapi',
    'Tarantula',
    'Waran z Komodo',
    'Axolotl',
    'Narwal',
    'Płaszczka',
    'Waran',
    'Legwan',
    'Kapibara',
    'Pangolin',
    'Tapir',
    'Wombat',
    'Koala',
    'Puma',
    'Jaguar',
    'Ocelot',
    'Ryś',
    'Borsuk',
    'Rosomak',
    'Fretka',
    'Suseł',
    'Piżmak',
    'Muflon',
    'Guanako',
    'Hiena',
    'Szakal',
    'Surykatka',
    'Mangusta',
    'Szop pracz',
    'Kakadu',
    'Koliber',
    'Tukan',
    'Struś',
    'Emu',
    'Kondor',
    'Żółw skórzasty',
    'Salamandra',
    'Traszka',
    'Mątwa',
    'Kałamarnica',
    'Meduza',
    'Palczak madagaskarski'
  ],
}
