import type { WordCategory } from './index'

export const classic: WordCategory = {
  id: 'classic',
  name: 'Klasyczne',
  wordsEasy: [
    'Krzesło',
    'Okulary',
    'Telefon',
    'Samolot',
    'Wiatrak',
    'Łóżko',
    'Stół',
    'Lampka',
    'Kubek',
    'Butelka',
    'Talerz',
    'Widelec',
    'Łyżka',
    'Nóż',
    'Garnek',
    'Patelnia',
    'Książka',
    'Zeszyt',
    'Długopis',
    'Ołówek',
    'Gumka',
    'Nożyczki',
    'Plecak',
    'Portfel',
    'Klucze',
    'Drzwi',
    'Okno',
    'Dywan',
    'Poduszka',
    'Koc',
    'Ręcznik',
    'Mydło',
    'Szczotka',
    'Grzebień',
    'Czapka',
    'Buty',
    'Skarpetki',
    'Kurtka',
    'Koszulka',
    'Spodnie',
    'Komputer',
    'Telewizor',
    'Pilot',
    'Ładowarka',
    'Zegar',
    'Kalendarz',
    'Wazon',
    'Roślina',
    'Świeczka',
    'Balon'
  ],
  wordsHard: [
    'Szachy',
    'Młotek',
    'Wulkan',
    'Parasol',
    'Lustro',
    'Kalejdoskop',
    'Korkociąg',
    'Mikroskop',
    'Gaśnica',
    'Odkurzacz',
    'Lornetka',
    'Teleskop',
    'Kompas',
    'Kostka Rubika',
    'Klepsydra',
    'Wahadło',
    'Barometr',
    'Termometr',
    'Higrometr',
    'Detektor dymu',
    'Wkrętarka',
    'Śrubokręt',
    'Szczypce',
    'Imadło',
    'Lutownica',
    'Dziurkacz',
    'Zszywacz',
    'Segregator',
    'Przybornik',
    'Tarka',
    'Cedzak',
    'Sito',
    'Młynek do kawy',
    'Ekspres do kawy',
    'Zmywarka',
    'Zamrażarka',
    'Wentylator sufitowy',
    'Panel słoneczny',
    'Bateria',
    'Powerbank',
    'Taśma miernicza',
    'Poziomnica',
    'Kask ochronny',
    'Kamizelka odblaskowa',
    'Apteczka',
    'Magnes neodymowy',
    'Szkło powiększające',
    'Zamek szyfrowy',
    'Przedłużacz',
    'Gilotyna do papieru'
  ],
}
