import type { WordCategory } from './index'

export const food: WordCategory = {
  id: 'food',
  name: 'Jedzenie',
  wordsEasy: [
    'Pizza',
    'Hamburger',
    'Lody',
    'Spaghetti',
    'Sałatka',
    'Zupa pomidorowa',
    'Rosół',
    'Naleśniki',
    'Pączek',
    'Kanapka',
    'Pierogi',
    'Bigos',
    'Kopytka',
    'Placki ziemniaczane',
    'Frytki',
    'Hot dog',
    'Tost',
    'Jajecznica',
    'Omlet',
    'Gofry',
    'Kiełbasa',
    'Kotlet schabowy',
    'Kurczak',
    'Ryż',
    'Makaron',
    'Kasza',
    'Ziemniaki',
    'Marchewka',
    'Ogórek',
    'Pomidor',
    'Jabłko',
    'Banan',
    'Truskawki',
    'Winogrona',
    'Czekolada',
    'Baton',
    'Ciastko',
    'Sernik',
    'Keks',
    'Babka',
    'Herbata',
    'Kawa',
    'Sok pomarańczowy',
    'Woda',
    'Lemoniada',
    'Popcorn',
    'Orzeszki',
    'Chipsy',
    'Ketchup',
    'Majonez'
  ],
  wordsHard: [
    'Sushi',
    'Tiramisu',
    'Ratatouille',
    'Carpaccio',
    'Krewetki w tempurze',
    'Ramen',
    'Pho',
    'Paella',
    'Boeuf bourguignon',
    'Risotto',
    'Gulasz węgierski',
    'Pad thai',
    'Tacos',
    'Burrito',
    'Nachos',
    'Focaccia',
    'Bruschetta',
    'Quiche',
    'Ceviche',
    'Moussaka',
    'Falafel',
    'Hummus',
    'Shakshuka',
    'Tabbouleh',
    'Baklava',
    'Panna cotta',
    'Crème brûlée',
    'Soufflé',
    'Gazpacho',
    'Bouillabaisse',
    'Pierś z kaczki',
    'Polędwica Wellington',
    'Stek z antrykotu',
    'Tatar wołowy',
    'Kluski śląskie',
    'Żurek',
    'Barszcz czerwony',
    'Gołąbki',
    'Babka ziemniaczana',
    'Kaszanka',
    'Pasztet',
    'Śledź w śmietanie',
    'Smalec z cebulką',
    'Kaczka po pekińsku',
    'Kimchi',
    'Tempura',
    'Sos béarnaise',
    'Sos holenderski',
    'Salsa verde',
    'Sałatka nicejska'
  ],
}
