import type { WordCategory } from './index'

export const movies: WordCategory = {
  id: 'movies',
  name: 'Filmy i seriale',
  wordsEasy: [
    'Titanic',
    'Matrix',
    'Shrek',
    'Avatar',
    'Incepcja',
    'Harry Potter',
    'Władca Pierścieni',
    'Król Lew',
    'Kraina lodu',
    'Toy Story',
    'Madagaskar',
    'Minionki',
    'Auta',
    'Coco',
    'Vaiana',
    'Potwory i spółka',
    'Gdzie jest Nemo',
    'Zaplątani',
    'Mulan',
    'Herkules',
    'Piękna i Bestia',
    'Księga dżungli',
    'Aladyn',
    'Ratatuj',
    'Kung Fu Panda',
    'Jak wytresować smoka',
    'Jumanji',
    'Jurassic Park',
    'Park Jurajski',
    'Piraci z Karaibów',
    'Kevin sam w domu',
    'Sami swoi',
    'Chłopaki nie płaczą',
    'Kiler',
    'Listy do M.',
    '007: Skyfall',
    'Rocky',
    'Rambo',
    'Terminator',
    'Obcy',
    'Predator',
    'E.T.',
    'Powrót do przyszłości',
    'Gremliny',
    'Faceci w czerni',
    'Spider-Man',
    'Batman',
    'Superman',
    'Avengers',
    'Kac Vegas'
  ],
  wordsHard: [
    'Ojciec chrzestny',
    'Forrest Gump',
    'Lot nad kukułczym gniazdem',
    'Gladiator',
    'Gwiezdne Wojny',
    'Skazani na Shawshank',
    'Pulp Fiction',
    'Zielona mila',
    'Siedem',
    'Podziemny krąg',
    'Blade Runner',
    'Mechaniczna pomarańcza',
    'Czas Apokalipsy',
    'Łowca jeleni',
    'Taxi Driver',
    'No Country for Old Men',
    'To nie jest kraj dla starych ludzi',
    'Amadeusz',
    'Piękny umysł',
    'Wyspa tajemnic',
    'Interstellar',
    '2001: Odyseja kosmiczna',
    'Dr Strangelove',
    'Zawrót głowy',
    'Obywatel Kane',
    'Truman Show',
    'Memento',
    'Requiem dla snu',
    'Labirynt fauna',
    'Życie jest piękne',
    'Stowarzyszenie Umarłych Poetów',
    'Człowiek z marmuru',
    'Człowiek z żelaza',
    'Kanał',
    'Ida',
    'Zimna wojna',
    'Wesele',
    'Dzień świra',
    'Pianista',
    'Miasto 44',
    'Zwierzęta nocy',
    'Zodiak',
    'Mulholland Drive',
    'Tamte dni, tamte noce',
    'Parasite',
    'Whiplash',
    'Wielki Gatsby',
    'Zabić drozda',
    'Infiltracja',
    'Siedem dusz'
  ],
}
