import type { WordCategory } from './index'

export const music: WordCategory = {
  id: 'music',
  name: 'Muzyka',
  wordsEasy: [
    'Gitara',
    'Pianino',
    'Perkusja',
    'Mikrofon',
    'Koncert',
    'Skrzypce',
    'Saksofon',
    'Trąbka',
    'Flet',
    'Bęben',
    'Piosenka',
    'Radio',
    'Słuchawki',
    'Głośnik',
    'Wzmacniacz',
    'DJ',
    'Karaoke',
    'Taniec',
    'Nuta',
    'Refren',
    'Zwrotka',
    'Rytm',
    'Melodia',
    'Wokal',
    'Chór',
    'Orkiestra',
    'Płyta',
    'Kaseta',
    'MP3',
    'Playlista',
    'Klaskanie',
    'Brawa',
    'Gwizdanie',
    'Takt',
    'Tempo',
    'Pauza',
    'Gama',
    'Akord',
    'Bas',
    'Solo',
    'Teledysk',
    'Scena',
    'Bilet',
    'Festiwal',
    'Próba',
    'Klawisze',
    'Tamburyn',
    'Harmonijka',
    'Ukulele',
    'Ksylofon'
  ],
  wordsHard: [
    'Chopin',
    'Beethoven',
    'Rock\'n\'roll',
    'Improwizacja',
    'Opera',
    'Dyrygent',
    'Kontrabas',
    'Altówka',
    'Wiolonczela',
    'Obój',
    'Klawesyn',
    'Syntezator',
    'Sampler',
    'Miksowanie',
    'Mastering',
    'Synkopa',
    'Polifonia',
    'Harmonia',
    'Aranżacja',
    'Partytura',
    'Symfonia',
    'Sonata',
    'Fuga',
    'Aria',
    'Balet',
    'Muzyka filmowa',
    'Muzyka klasyczna',
    'Jazz',
    'Blues',
    'Metal progresywny',
    'Hip-hop',
    'Reggae',
    'Elektronika',
    'House',
    'Techno',
    'Bossa nova',
    'Flamenco',
    'Muzyka ludowa',
    'Beatbox',
    'Scat',
    'Improwizacja jazzowa',
    'Skala pentatoniczna',
    'Słuch absolutny',
    'Chór gospel',
    'Koncert kameralny',
    'Próba dźwięku',
    'Występ na bis',
    'Instrumenty dęte',
    'Sekcja rytmiczna',
    'Metrum'
  ],
}
