import type { WordCategory } from './index'

export const places: WordCategory = {
  id: 'places',
  name: 'Miejsca',
  wordsEasy: [
    'Szkoła',
    'Kino',
    'Plaża',
    'Las',
    'Restauracja',
    'Dom',
    'Mieszkanie',
    'Sklep',
    'Supermarket',
    'Plac zabaw',
    'Park',
    'ZOO',
    'Basen',
    'Siłownia',
    'Boisko',
    'Biblioteka',
    'Poczta',
    'Apteka',
    'Szpital',
    'Przychodnia',
    'Kościół',
    'Ratusz',
    'Rynek',
    'Dworzec',
    'Lotnisko',
    'Przystanek',
    'Ulica',
    'Most',
    'Tunel',
    'Stacja benzynowa',
    'Hotel',
    'Kawiarnia',
    'Piekarnia',
    'Centrum handlowe',
    'Muzeum',
    'Teatr',
    'Galeria',
    'Stadion',
    'Sala koncertowa',
    'Kemping',
    'Góry',
    'Jezioro',
    'Rzeka',
    'Wyspa',
    'Wioska',
    'Miasto',
    'Wieś',
    'Ogród',
    'Piwnica',
    'Strych'
  ],
  wordsHard: [
    'Louvre',
    'Wielki Mur Chiński',
    'Wieża Eiffla',
    'Koloseum',
    'Machu Picchu',
    'Statua Wolności',
    'Big Ben',
    'Opera w Sydney',
    'Tadż Mahal',
    'Sagrada Família',
    'Pałac Buckingham',
    'Kreml',
    'Akropol',
    'Petra',
    'Angkor Wat',
    'Mount Everest',
    'Wielki Kanion',
    'Niagara',
    'Wodospad Iguazu',
    'Sahara',
    'Amazonia',
    'Wenecja',
    'Dubaj',
    'Singapur',
    'Hongkong',
    'Pola Elizejskie',
    'Times Square',
    'Złota Brama',
    'Alcatraz',
    'Las Vegas Strip',
    'Stare Miasto w Krakowie',
    'Wawel',
    'Morskie Oko',
    'Kopalnia Soli w Wieliczce',
    'Białowieża',
    'Gdańska Starówka',
    'Zakopane',
    'Hel',
    'Malbork',
    'Jasna Góra',
    'Pomnik Chrystusa w Rio',
    'Stonehenge',
    'Piramidy w Gizie',
    'Cappadocia',
    'Borobudur',
    'Wyspa Wielkanocna',
    'Przylądek Dobrej Nadziei',
    'Morze Martwe',
    'Wyspa Santorini',
    'Czarnobyl'
  ],
}
