import type { WordCategory } from './index'

export const professions: WordCategory = {
  id: 'professions',
  name: 'Zawody',
  wordsEasy: [
    'Lekarz',
    'Strażak',
    'Policjant',
    'Nauczyciel',
    'Kucharz',
    'Fryzjer',
    'Kasjer',
    'Kierowca',
    'Sprzedawca',
    'Piekarz',
    'Pielęgniarka',
    'Mechanik',
    'Hydraulik',
    'Elektryk',
    'Stolarz',
    'Murarz',
    'Ogrodnik',
    'Rolnik',
    'Listonosz',
    'Kelner',
    'Barista',
    'Szatniarz',
    'Portier',
    'Recepcjonista',
    'Taksówkarz',
    'Kurier',
    'Magazynier',
    'Sprzątacz',
    'Ochroniarz',
    'Trener',
    'Wychowawca',
    'Bibliotekarz',
    'Weterynarz',
    'Dentysta',
    'Farmaceuta',
    'Pilot',
    'Stewardesa',
    'Fotograf',
    'Krawiec',
    'Malarz',
    'Księgowy',
    'Programista',
    'Grafik',
    'Muzyk',
    'Piosenkarz',
    'Aktor',
    'Tancerz',
    'Kominiarz',
    'Zegarmistrz',
    'Ratownik'
  ],
  wordsHard: [
    'Astronauta',
    'Neurochirurg',
    'Archeolog',
    'Detektyw',
    'Aktor dubbingowy',
    'Kontroler lotów',
    'Geodeta',
    'Analityk danych',
    'Tłumacz symultaniczny',
    'Inżynier budowlany',
    'Architekt',
    'Audytor',
    'Biegły rewident',
    'Prokurator',
    'Notariusz',
    'Sędzia',
    'Kurator sądowy',
    'Broker ubezpieczeniowy',
    'Makler giełdowy',
    'Aktuariusz',
    'Specjalista ds. SEO',
    'Administrator sieci',
    'Tester oprogramowania',
    'DevOps',
    'Data scientist',
    'Chemik analityk',
    'Biotechnolog',
    'Fizyk medyczny',
    'Radiolog',
    'Anestezjolog',
    'Logopeda',
    'Fizjoterapeuta',
    'Terapeuta zajęciowy',
    'Psychoterapeuta',
    'Neonatolog',
    'Rzeczoznawca majątkowy',
    'Kierownik produkcji',
    'Operator CNC',
    'Kontroler jakości',
    'Projektant UX',
    'Scenograf',
    'Reżyser dźwięku',
    'Producent filmowy',
    'Montażysta',
    'Lektor',
    'Korespondent wojenny',
    'Kapitan statku',
    'Pilot drona',
    'Konserwator zabytków',
    'Kryptolog'
  ],
}
