import type { WordCategory } from './index'

export const random: WordCategory = {
  id: 'random',
  name: 'Przysłowia',
  wordsEasy: [
    'Bez pracy nie ma kołaczy.',
    'Czas leczy rany.',
    'Co nagle, to po diable.',
    'Głodnemu chleb na myśli.',
    'Jak sobie pościelesz, tak się wyśpisz.',
    'Lepszy wróbel w garści niż gołąb na dachu.',
    'Nie chwal dnia przed zachodem słońca.',
    'Darowanemu koniowi w zęby się nie zagląda.',
    'Kto późno przychodzi, sam sobie szkodzi.',
    'Gdzie kucharek sześć, tam nie ma co jeść.',
    'Nie ma róży bez kolców.',
    'Jak Kuba Bogu, tak Bóg Kubie.',
    'Kto pod kim dołki kopie, ten sam w nie wpada.',
    'Nie wszystko złoto, co się świeci.',
    'Cicha woda brzegi rwie.',
    'Co ma wisieć, nie utonie.',
    'Nie wywołuj wilka z lasu.',
    'Diabeł tkwi w szczegółach.',
    'Lepiej zapobiegać niż leczyć.',
    'Co dwie głowy, to nie jedna.',
    'Polak potrafi.',
    'Zgoda buduje, niezgoda rujnuje.',
    'Nie ma dymu bez ognia.',
    'Ucz się na błędach.',
    'Apetyt rośnie w miarę jedzenia.',
    'Nie taki diabeł straszny.',
    'Lepszy rydz niż nic.',
    'Jak trwoga, to do Boga.',
    'Gość w dom, Bóg w dom.',
    'Przez żołądek do serca.',
    'Stara miłość nie rdzewieje.',
    'Co z oczu, to z serca.',
    'Nie mów hop, póki nie przeskoczysz.',
    'Jak nie urok, to przemarsz.',
    'Kto pierwszy, ten lepszy.',
    'Słowo się rzekło.',
    'Mądry Polak po szkodzie.',
    'Grosz do grosza.',
    'Do trzech razy sztuka.',
    'Gdzie jest wola, tam jest droga.',
    'Kto nie ryzykuje, nie pije szampana.',
    'Złapać byka za rogi.',
    'Wszystko ma swój czas.',
    'Człowiek człowiekowi wilkiem.',
    'Nie ma tego złego.',
    'Każdy kij ma dwa końce.',
    'Jaki pan, taki kram.',
    'Kto sieje wiatr, zbiera burzę.',
    'Dzieci i ryby głosu nie mają.',
    'Nie ma tego złego, co by na dobre nie wyszło.'
  ],
  wordsHard: [
    'Nie od razu Kraków zbudowano.',
    'Leje jak z cebra.',
    'Siedzieć jak na szpilkach.',
    'Rzucać grochem o ścianę.',
    'Szukać igły w stogu siana.',
    'Wpaść z deszczu pod rynnę.',
    'Wyjść jak Zabłocki na mydle.',
    'Nie dla psa kiełbasa.',
    'Trafiła kosa na kamień.',
    'Nosił wilk razy kilka, ponieśli i wilka.',
    'Bujać w obłokach.',
    'Rzucać słowa na wiatr.',
    'Wziąć nogi za pas.',
    'Zrobić z igły widły.',
    'Palnąć jak filip z konopi.',
    'Robić dobrą minę do złej gry.',
    'Być między młotem a kowadłem.',
    'Iść po trupach do celu.',
    'Mieć muchy w nosie.',
    'Być w siódmym niebie.',
    'Trzymać język za zębami.',
    'Wyjść na prostą.',
    'Kupić kota w worku.',
    'Spuścić z tonu.',
    'Rzucić wszystko i wyjechać w Bieszczady.',
    'Zjeść na czymś zęby.',
    'Nie dać sobie w kaszę dmuchać.',
    'Mieć ręce pełne roboty.',
    'Pójść na całość.',
    'Zacisnąć zęby.',
    'Wyszedł szydło z worka.',
    'Wpaść jak śliwka w kompot.',
    'Wystawić kogoś do wiatru.',
    'Dać komuś kosza.',
    'Zrobić komuś wodę z mózgu.',
    'Obrócić kota ogonem.',
    'Patrzeć przez różowe okulary.',
    'Postawić kropkę nad i.',
    'Złapać drugi oddech.',
    'Mieć dwie lewe ręce.',
    'Sypać jak z rękawa.',
    'Wyjść przed szereg.',
    'Dla świętego spokoju.',
    'Wziąć sprawy w swoje ręce.',
    'Iść na żywioł.',
    'Zbić kogoś z tropu.',
    'Wypić piwo, które się nawarzyło.',
    'Zamienić się w słup soli.',
    'Zrobić coś na ostatnią chwilę.',
    'Zakochać się po uszy.'
  ],
}
