import type { WordCategory } from './index'

export const random: WordCategory = {
  id: 'random',
  name: 'Przysłowia',
  wordsEasy: [
    'Bez pracy nie ma kołaczy',
    'Co nagle, to po diable',
    'Głodnemu chleb na myśli',
    'Jak sobie pościelesz, tak się wyśpisz',
    'Lepszy wróbel w garści niż gołąb na dachu',
    'Darowanemu koniowi w zęby się nie zagląda',
    'Gdzie kucharek sześć, tam nie ma co jeść',
    'Kto pod kim dołki kopie, ten sam w nie wpada',
    'Nie wywołuj wilka z lasu',
    'Apetyt rośnie w miarę jedzenia',
    'Nie taki diabeł straszny, jak go malują',
    'Gość w dom, Bóg w dom',
    'Przez żołądek do serca',
    'Nie mów hop, póki nie przeskoczysz',
    'Kto nie ryzykuje, nie pije szampana',
    'Kto rano wstaje, temu Pan Bóg daje',
    'Niedaleko pada jabłko od jabłoni',
    'Krowa, która dużo ryczy, mało mleka daje',
    'Wilk syty i owca cała',
    'Nie kupuj kota w worku',
    'Ręka rękę myje',
    'Gdzie drwa rąbią, tam wióry lecą',
    'Z pustego i Salomon nie naleje',
    'Strach ma wielkie oczy',
    'Pierwsze koty za płoty',
    'Kto nie ma w głowie, ten ma w nogach',
    'Z deszczu pod rynnę',
    'Uderz w stół, a nożyce się odezwą',
    'Baba z wozu, koniom lżej',
    'Nie ma tego złego, co by na dobre nie wyszło',
    'Kto pyta, nie błądzi',
    'Kłamstwo ma krótkie nogi',
    'Fortuna kołem się toczy',
    'Raz na wozie, raz pod wozem',
    'Tonący brzytwy się chwyta',
    'Kto mieczem wojuje, od miecza ginie',
    'Nie ma dymu bez ognia',
    'Nie wszystko złoto, co się świeci',
    'Cicha woda brzegi rwie',
    'Nie ma róży bez kolców',
    'Jak Kuba Bogu, tak Bóg Kubie',
    'Stara miłość nie rdzewieje',
    'Co z oczu, to z serca',
    'Grosz do grosza, a będzie kokosza',
    'Lepszy rydz niż nic',
    'Jak trwoga, to do Boga',
    'Kto pierwszy, ten lepszy',
    'Do trzech razy sztuka',
    'Każdy kij ma dwa końce',
    'Dzieci i ryby głosu nie mają',
    'Na złodzieju czapka gore',
    'Gdzie dwóch się bije, tam trzeci korzysta',
    'Nie dziel skóry na niedźwiedziu',
    'Gdy kota nie ma, myszy harcują',
    'Ślepej kurze ziarno się trafi',
    'Szewc bez butów chodzi',
    'Gdyby kózka nie skakała, toby nóżki nie złamała',
    'Kto z kim przestaje, takim się staje',
    'Każda potwora znajdzie swego amatora',
    'Nie ucz ojca dzieci robić',
    'Nie ucz księdza pacierza',
    'Przyszła kryska na Matyska',
    'Kto się czubi, ten się lubi',
    'Kto daje i odbiera, ten się w piekle poniewiera',
    'Do odważnych świat należy',
    'Nie od razu Kraków zbudowano',
    'W zdrowym ciele zdrowy duch',
    'Czego oczy nie widzą, tego sercu nie żal',
    'Nie święci garnki lepią',
    'Kto smaruje, ten jedzie',
    'Jak się nie ma, co się lubi, to się lubi, co się ma',
    'Lepiej późno niż wcale',
    'Robota nie zając, nie ucieknie',
    'Nie mój cyrk, nie moje małpy',
    'Kto bogatemu zabroni',
    'Polak potrafi',
    'Cudze chwalicie, swego nie znacie',
    'Mowa jest srebrem, a milczenie złotem',
    'Prawdziwych przyjaciół poznaje się w biedzie',
    'Kto zjada ostatki, ten piękny i gładki',
    'Nie rób drugiemu, co tobie niemiłe',
    'Mądry Polak po szkodzie',
    'Nie dla psa kiełbasa',
    'Nie samym chlebem człowiek żyje',
    'Nie śmiej się dziadku z czyjegoś wypadku',
    'Nie płacz nad rozlanym mlekiem',
    'Lepiej dmuchać na zimne',
    'Młodość musi się wyszumieć',
    'Jak się człowiek spieszy, to się diabeł cieszy',
    'Jaka praca, taka płaca',
    'Jaki ojciec, taki syn',
    'Raz się żyje',
    'Do tanga trzeba dwojga',
    'Baba o szydle, dziad o mydle',
    'Bez mąki chleba nie upieczesz',
    'Chciwy dwa razy traci',
    'Co cię nie zabije, to cię wzmocni',
    'Co kraj, to obyczaj',
    'Co za dużo, to niezdrowo',
    'Człowiek uczy się całe życie',
    'Koniec języka za przewodnika',
    'Koniec wieńczy dzieło',
    'Każdy orze, jak może',
    'Każdy ma swoje pięć minut',
    'Kto szuka, ten znajdzie',
    'Kuj żelazo, póki gorące',
    'Licho nie śpi',
    'Małe dzieci, mały kłopot; duże dzieci, duży kłopot',
    'Oko za oko, ząb za ząb',
    'Pies ogrodnika sam nie zje i drugiemu nie da',
    'Pisać jak kura pazurem',
    'Płacić jak za zboże',
    'Przyczepić się jak rzep psiego ogona',
    'Trafić kulą w płot',
    'Z dużej chmury mały deszcz',
    'Czego Jaś się nie nauczy, tego Jan nie będzie umiał',
    'Złapać byka za rogi',
    'Robić dobrą minę do złej gry',
    'Dać serce na dłoni',
    'Bujać w obłokach',
    'Mieć dwie lewe ręce',
    'Wziąć nogi za pas',
    'Trzymać język za zębami',
    'Patrzeć przez różowe okulary',
    'Nie kopię się leżącego',
    'Wpaść jak śliwka w kompot',
    'Zamienić się w słup soli',
    'Nie dać sobie w kaszę dmuchać',
    'Robić z igły widły',
    'Siedzieć jak na szpilkach',
    'Szukać igły w stogu siana',
    'Rzucać grochem o ścianę',
    'Leje jak z cebra',
    'Twardy orzech do zgryzienia',
    'Mieć oczy dookoła głowy',
    'Ciągnąć kogoś za język',
    'Znać coś jak własną kieszeń',
    'Albo rybki, albo akwarium',
    'Złapać Pana Boga za nogi',
    'Wstać lewą nogą',
    'Spać jak suseł',
    'Zdrowy jak ryba',
    'Uparty jak osioł',
    'Wolny jak żółw',
    'Pracowity jak mrówka',
    'Dumny jak paw',
    'Cichy jak mysz pod miotłą',
    'Pasuje jak pięść do nosa',
    'Iść jak po maśle',
    'Mieć asa w rękawie',
    'Mieć nóż na gardle',
    'Mieć coś na końcu języka',
    'Mieć ręce pełne roboty',
    'Wyciągnąć pomocną dłoń',
    'Kamień spadł z serca',
    'Serce podchodzi do gardła',
    'Wodzić kogoś za nos',
    'Ściany mają uszy',
    'Włożyć kij w mrowisko',
    'Dolać oliwy do ognia',
    'Żyć jak pączek w maśle',
    'Ostatnia deska ratunku',
    'Zapędzić kogoś w kozi róg',
    'Podkładać komuś świnię',
    'Wyskoczyć jak Filip z konopi',
    'Piąte koło u wozu',
    'Mydlić komuś oczy',
    'Mieć węża w kieszeni',
    'Zrobić kogoś w konia',
    'Patrzeć komuś na ręce',
    'Trzymać rękę na pulsie',
    'Nabić kogoś w butelkę',
    'Nabrać wody w usta',
    'Mieć kamienną twarz',
    'Złapać wiatr w żagle',
    'Co się odwlecze, to nie uciecze',
    'Wszędzie dobrze, ale w domu najlepiej',
    'W przyrodzie nic nie ginie',
    'Lepiej zapobiegać niż leczyć',
    'Co dwie głowy, to nie jedna',
    'Wyjść na ludzi',
    'Jak cię widzą, tak cię piszą',
    'Miłe złego początki',
    'Każdy jest kowalem swojego losu',
    'Gdzie diabeł nie może, tam babę pośle',
    'Trafiła kosa na kamień',
    'Być między młotem a kowadłem',
    'Wyszło szydło z worka',
    'Wystawić kogoś do wiatru',
    'Obrócić kota ogonem',
    'Zjeść na czymś zęby',
    'Czuć pismo nosem',
    'Nawijać makaron na uszy',
    'Obiecywać gruszki na wierzbie',
    'Palić za sobą mosty',
    'Wpuszczać kogoś w maliny',
    'Wracać z podkulonym ogonem',
    'Zamknąć buzię na kłódkę',
    'Tłumaczyć z polskiego na nasze',
  ],
  wordsHard: [
    'Czym skorupka za młodu nasiąknie, tym na starość trąci',
    'Kiedy wejdziesz między wrony, musisz krakać jak i one',
    'Pokorne cielę dwie matki ssie',
    'Głową muru nie przebijesz',
    'Jedna jaskółka wiosny nie czyni',
    'Prawda w oczy kole',
    'Prawda jak oliwa zawsze na wierzch wypływa',
    'Ciekawość to pierwszy stopień do piekła',
    'Łatwo przyszło, łatwo poszło',
    'Każdy medal ma dwie strony',
    'Serce nie sługa',
    'Człowiek wyjedzie z wsi ale wieś z człowieka nigdy',
    'Nie wchodzi się dwa razy do tej samej rzeki',
    'Nie rzucaj pereł przed wieprze',
    'Lepiej mądrze stać, niż głupio biegać',
    'Lepiej z mądrym zgubić, niż z głupim znaleźć',
    'Jaki kraj, taki obyczaj',
    'Baba swoje, czart swoje',
    'Co było, a nie jest, nie pisze się w rejestr',
    'Człowiek strzela, Pan Bóg kule nosi',
    'Daj kurze grzędę, a ona wyżej siędzie',
    'Gdyby babcia miała wąsy, toby była dziadkiem',
    'Gdy bieda wchodzi drzwiami, miłość wychodzi oknem',
    'Gra niewarta świeczki',
    'Każdy sobie rzepkę skrobie',
    'W gorączej wodzie kąpany',
    'Nosił wilk razy kilka, ponieśli i wilka',
    'Wyżej dupy nie podskoczysz',
    'Zgoda buduje, niezgoda rujnuje',
    'Kto sieje wiatr, zbiera burzę',
    'Daj palec, a weźmie całą rękę',
    'Jeden rabin powie tak, drugi rabin powie nie',
    'Kto ma pszczoły, ten ma miód',
    'Człowiek człowiekowi wilkiem',
    'Miłość jest ślepa',
    'Nadzieja matką głupich',
    'Kto późno przychodzi, sam sobie szkodzi',
    'Diabeł tkwi w szczegółach',
    'Ucz się na błędach',
    'Wszystkie drogi prowadzą do Rzymu',
    'Kto nie idzie do przodu, ten się cofa',
    'Łaska pańska na pstrym koniu jeździ',
    'Chcesz pokoju, szykuj się do wojny',
    'Mądry głupiemu ustępuje',
    'Chcesz liczyć na innych, licz na siebie',
    'Wyjść jak Zabłocki na mydle',
    'Iść po trupach do celu',
    'Zrobić komuś wodę z mózgu',
    'Wziąć sprawy w swoje ręce',
    'Iść na żywioł',
    'Nawarzyłeś piwa, to je wypij',
    'Rzucić wszystko i wyjechać w Bieszczady',
    'Zrobić coś na ostatnią chwilę',
    'Mieć związane ręce',
    'Mówić przez zęby',
    'Mówić z ręką na sercu',
    'Na dwoje babka wróżyła',
    'Nalewać z pustego w próżne',
    'Otwierać puszkę Pandory',
    'Piąta woda po kisielu',
    'Upiec dwie pieczenie na jednym ogniu',
    'Podcinać komuś skrzydła',
    'Podkładać komuś kłody pod nogi',
    'Przelewać z pustego w próżne',
    'Rzucać się z motyką na słońce',
    'Stawiać sprawę na ostrzu noża',
    'Szukać wiatru w polu',
    'Szyć grubymi nićmi',
    'Śmiać się przez łzy',
    'Tańczyć, jak ktoś zagra',
    'Uciekać, gdzie pieprz rośnie',
    'Uciekać, gdzie raki zimują',
    'Wiercić komuś dziurę w brzuchu',
    'Wtykać nos w nie swoje sprawy',
    'Zawracać Wisłę kijem',
    'Zjeść ciastko i mieć ciastko',
    'Złapać kogoś na gorącym uczynku',
    'Co za dużo, to i świnia nie zeżre',
    'Jak kraść, to miliony',
    'Nie ma takiej rury, której nie można odetkać',
    'Mieć kij w dupie',
    'Kto pije i pali, ten nie ma robali',
    'Dupa nie szklanka, nie pęknie',
    'Mieć wszystko w dupie',
    'Jaja jak berety',
    'Wyjść z gołą dupą na mróz',
    'Wchodzić komuś w dupę',
    'Zabrać dupę w troki',
    'Mieć jaja ze stali',
    'Pieprzyć trzy po trzy',
    'Pieprzyć jak potłuczony',
    'Mieć mokro w majtkach',
    'Mieć kisiel w majtkach',
    'Rzygać jak kot',
    'Rzygać dalej niż widzieć',
    'Morda nie szklanka',
    'Napalić się jak szczerbaty na suchary',
    'Co wolno wojewodzie, to nie tobie, smrodzie',
    'Nie ma głupich pytań, są tylko głupie odpowiedzi',
    'Głupi ma zawsze szczęście',
    'Kto nie pije, ten podpierdala',
    'Chuj bombki strzelił, choinki nie będzie',
    'Z gówna bata nie ukręcisz',
    'Nie ruszaj gówna, bo śmierdzi',
    'Nie ma chuja we wsi',
    'Kto ma miękkie serce, musi mieć twardą dupę',
    'Lepszy brzuch od piwa niż garb od roboty',
    'Alkohol pity z umiarem nie szkodzi nawet w dużych ilościach',
  ],
}
