import type { WordCategory } from './index'

export const sport: WordCategory = {
  id: 'sport',
  name: 'Sport',
  wordsEasy: [
    'Piłka nożna',
    'Koszykówka',
    'Tenis',
    'Siatkówka',
    'Bieganie',
    'Pływanie',
    'Rower',
    'Narciarstwo',
    'Łyżwiarstwo',
    'Ping-pong',
    'Boks',
    'Gimnastyka',
    'Skakanka',
    'Hula-hop',
    'Kibic',
    'Bramka',
    'Piłka',
    'Trener',
    'Sędzia',
    'Stadion',
    'Rzut karny',
    'Rzut wolny',
    'Podanie',
    'Strzał',
    'Gol',
    'Maraton',
    'Sprint',
    'Rozgrzewka',
    'Stretching',
    'Mecz',
    'Turniej',
    'Medal',
    'Puchar',
    'Flaga',
    'Gwizdek',
    'Zawodnik',
    'Drużyna',
    'Ławka rezerwowych',
    'Dogrywka',
    'Remis',
    'Rzut rożny',
    'Spalony',
    'Serwis',
    'As',
    'Punkt',
    'Set',
    'Gem',
    'Runda',
    'Finał',
    'Zwycięstwo'
  ],
  wordsHard: [
    'Triathlon',
    'Wspinaczka sportowa',
    'Skoki narciarskie',
    'Boks tajski',
    'Żeglarstwo',
    'Szermierka',
    'Łucznictwo',
    'Kolarstwo torowe',
    'Biathlon',
    'Snowboard',
    'Kajakarstwo górskie',
    'Wioślarstwo',
    'Piłka ręczna',
    'Hokej na lodzie',
    'Rugby',
    'Baseball',
    'Cricket',
    'Badminton',
    'Squash',
    'Golf',
    'Judo',
    'Karate',
    'Taekwondo',
    'Zapasy',
    'Podnoszenie ciężarów',
    'Gimnastyka artystyczna',
    'Łyżwiarstwo figurowe',
    'Skoki do wody',
    'Pływanie synchroniczne',
    'Bobsleje',
    'Saneczkarstwo',
    'Biegi narciarskie',
    'Nordic walking',
    'Parkour',
    'Crossfit',
    'Windsurfing',
    'Kitesurfing',
    'Nurkowanie',
    'Orientacja sportowa',
    'Wielobój',
    'Rzut oszczepem',
    'Rzut dyskiem',
    'Pchnięcie kulą',
    'Skok wzwyż',
    'Skok w dal',
    'Pięciobój nowoczesny',
    'Formuła 1',
    'Rajd samochodowy',
    'Wspinaczka wysokogórska',
    'Slackline'
  ],
}
